### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Dhia010** [thanhvule0310/themes-for-cmder#1]
It's not really an issue but a question, how did you add the folder and file icons to cmder like in the previews?

**Comment by teddy2104** [comment]
> Sorry for a reply too late, It depends on what shell you using:
> 
> For windows (cmd, powershell, gitbash, cmder):
> 
> * [Terminal-Icons](https://github.com/devblackops/Terminal-Icons) only work for powershell
> * [logo-ls](https://github.com/Yash-Handa/logo-ls)
> * [lsd](https://github.com/Peltoche/lsd)
> 
> For Windows with WSL or Linux, MacOS (bash, zsh,...):
> 
> * [exa](https://github.com/ogham/exa)
> * logo-ls, lsd also available
> 
> Ask me anything if you want more help beers

Nice!

**Comment by Dhia010** [comment]
> Sorry for a reply too late, It depends on what shell you using:
> 
> For windows (cmd, powershell, gitbash, cmder):
> 
> * [Terminal-Icons](https://github.com/devblackops/Terminal-Icons) only work for powershell
> * [logo-ls](https://github.com/Yash-Handa/logo-ls)
> * [lsd](https://github.com/Peltoche/lsd)
> 
> For Windows with WSL or Linux, MacOS (bash, zsh,...):
> 
> * [exa](https://github.com/ogham/exa)
> * logo-ls, lsd also available
> 
> Ask me anything if you want more help 🍻

thank you!
